### ISSUE TITLE
Getting invalid composer file after cloning repo

### ISSUE THREAD

**Issue by zaifastafa** [FriendsOfShopware/FroshPluginUploader#108]
After cloning the repository and doing `plugin:refresh` I get this error: 

` [ERROR] The file "/var/www/html/custom/plugins/FroshPluginUploader/composer.json" is invalid. Errors:              
         Plugin composer.json has invalid "type" (must be "shopware-platform-plugin"), or invalid                       
         "extra/shopware-plugin-class" value, or missing extra.label property        `

The plugin which is supposed to validate other plugins is having its own validation issues? 😄 Or am I missing something?

**Comment by teiling88** [comment]
Just a simple quote from the readme, maybe you get the point ;-) 

```Tool for uploading new plugin releases to Shopware Store```

**Comment by zaifastafa** [comment]
@teiling88 So it works without installation?

**Comment by teiling88** [comment]
> So it works without installation?

Installation in shopware? yes
Without composer install? no
Maybe you should use the docker image for that.

**Comment by shyim** [comment]
Its a own php project and not a shopware plugin
