### ISSUE TITLE
Modification of composer.json is useless

### ISSUE THREAD

**Issue by avdv** [FriendsOfShopware/FroshPluginUploader#112]
In the ext:prepare step, the `composer.json` file is modified to remove several dependencies from `require`:
```php
        $keys = ['shopware/platform', 'shopware/core', 'shopware/storefront', 'shopware/administration', 'composer/installers'];
        foreach ($keys as $key) {
            if (isset($json['require'][$key])) {
                unset($json['require'][$key]);
            }
        }
```
Afterwards, `composer install` is called.

This has no effect overall, if you have a `composer.lock` file, since composer will prefer the lock file over the json and just emit a warning that the hash does not match:
```
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
```
Is it a bad idea to use a lock file with Shopware plugins?

But then, if there is no lock file, calling `composer install` is not the right thing to do (there is a warning when the lock file is missing), and it basically does the same as `composer update`.

Seems to me that calling composer update is the only sensible thing in this case... WDYT?

**Comment by shyim** [comment]
You are right. We should remove that file before running composer install. Are you interested in building a PR?

**Comment by avdv** [comment]
For now, I have just marked the `composer.lock` file as `export-ignore` in `.gitattributes.

> You are right. We should remove that file before running composer install. Are you interested in building a PR?

Sure, can do. Where should this be removed? Simply add it the list of excluded files or simply call `unlink` before `composer install` or use `composer update`?

**Comment by shyim** [comment]
I would unlink it if exists in Uploader Code
