### ISSUE TITLE
English highlights, description and label not updated in store

### ISSUE THREAD

**Issue by avdv** [FriendsOfShopware/FroshPluginUploader#113]
Hi.

I am using `FroshPluginUploader 0.3.9`, I have the following files in the store folder:
```console
$ ls Resources/store/ -1
de_faq.md
de_features.txt
de_highlights.txt
de_manual.md
de.md
en_faq.md
en_features.txt
en_highlights.txt
en_manual.md
en.md
icon.png
images
store.json
```
After running `ext:update .` the german highlights (for example) are updated, but the english highlights are still empty -- actually *all* english entries are still empty...

What am I missing?

**Comment by shyim** [comment]
Can you try to write something in a english field save and run it again?

**Comment by avdv** [comment]
I think I tried that already... :thinking: 

When I request the plugin data via the API, there is an entry for `en_GB` in the `infos` field:
```json
       {
            "description": "",
            "faqs": [],
            "features": "",
            "highlights": "",
            "id": 22491,
            "installationManual": "",
            "locale": {
                "id": 2,
                "name": "en_GB"
            },
            "name": "Test",
            "shortDescription": "",
            "tags": [],
            "videos": []
        }
```
But now, after re-running the `ext:update` command, the data is stored.

Note, I had created the plugin in the store using `ext:validate --create file.zip`.

**Comment by shyim** [comment]
Ahh. ext:update needs to add the missing info when missing
