### ISSUE TITLE
Markdown parser produces incorrect results

### ISSUE THREAD

**Issue by avdv** [FriendsOfShopware/FroshPluginUploader#115]
(I had a concrete code example, but I think this is really not relevant).

Current situation is: everything looks good in Gitlab / Github / Visual Studio Code markdown preview, and it comes out broken using the plugin-updater.

I see that parsedown is used as a Markdown parser. I checked with their [online demo](https://parsedown.org/demo) and it's broken too (the result for Markdown PHP 1.3 is OK).

It seems that this thing is not very compliant with commonmark or even original markdown (using a simple `<p>` tag makes it choke); and also seems to be unmaintained, with 70 open issues and 45 open pull requests.

They say it's fast, but I don't really care about how fast the parser is, I would prefer it to be correct.

I'd be up to create a PR ripping it out and replacing with another library. Thoughts?

**Comment by shyim** [comment]
Maybe it makes sense to replace it with https://packagist.org/packages/league/commonmark ?

**Comment by avdv** [comment]
> Maybe it makes sense to replace it with [packagist.org/packages/league/commonmark](https://packagist.org/packages/league/commonmark) ?

Yes, this looks really good. Also, it's extensible / configurable. PR coming up...
