### ISSUE TITLE
How to prevent adding dependencies for plugin targeting 6.4?

### ISSUE THREAD

**Issue by avdv** [FriendsOfShopware/FroshPluginUploader#163]
Hi.

Shopware 6.4 now calls `composer require`if a plugin's `executeComposerCommands` method returns true.

How can I use this with the plugin uploader? I would like to skip all the composer magic that this thing does and defer it to the actual installation. 

Thanks!

**Comment by shyim** [comment]
That feature is still in work and disabled by default in 6.4.

**Comment by avdv** [comment]
Really? :astonished: Just read this here: https://github.com/shopware/development/pull/141

> In v6.4.0.0 Shopware will add support for plugins which manage their dependencies via composer:

Too bad.

**Comment by mitelg** [comment]
it was planned, but short before the release, we found issues, which we could not solve until the stable 6.4.0.0 release. 
so unfortunately we decided to postpone this change for the next major version

**Comment by avdv** [comment]
@mitelg  got it, thanks!
