### ISSUE TITLE
Shopware 6 sources are included in package

### ISSUE THREAD

**Issue by moehrenzahn** [FriendsOfShopware/FroshPluginUploader#17]
First, thanks for this incredibly useful tool!

I have one question: When building a zip package using `pluginupload plugin:zip:dir . master` the finished ZIP file includes the sources from `shopware/storefront`, `shopware/core`, etc. in  `vendor/shopware`. These are a little more than 50 MB in size.

I am wondering if this is a bug of if there is a reason to include these sources.

## Expected

- `vendor/shopware` is not included in plugin .zip packages.

## Actual

- `vendor/shopware` is included in plugin .zip packages, duplicating source code when installing the plugin 

## Suggestion

There already is some logic to strip the `shopware` packages from the `composer.json` in `FroshPluginUploader\Components\PluginZip::needComposerToRun`, it would be easy to update the temporary `composer.json` so the Shopware sources are not added to the package during `composer install`.

What do you think?

**Comment by shyim** [comment]
My main problem is that Shopware 6 currently don't have an solution for that. Anything else is a hack. 
Maybe your suggestion could be a Workaround for now. Could you create an PR?

**Comment by moehrenzahn** [comment]
Sure, I'll get back to you!

**Comment by shyim** [comment]
@moehrenzahn Maybe we can use this as base?
https://github.com/FriendsOfShopware/FroshDevelopmentHelper/blob/master/vendor-builder.php

**Comment by shyim** [comment]
Ahh we did built already something. Just forgot to close the issue
