### ISSUE TITLE
Images for a specific language

### ISSUE THREAD

**Issue by momocode-de** [FriendsOfShopware/FroshPluginUploader#20]
It seems like all images I'm adding to the "Resources/store/images" folder are activated for all languages on default. But I have screenshots of my plugin for each language and when I upload my images on the shopware account I can deselect languages for specific images.

It would be great if I can do the same with this plugin uploader.

**Comment by shyim** [comment]
See updated docs https://github.com/FriendsOfShopware/FroshPluginUploader/wiki/Resources-store-Folder
