### ISSUE TITLE
Including non-version-controlled sources in plugin:zip:dir

### ISSUE THREAD

**Issue by moehrenzahn** [FriendsOfShopware/FroshPluginUploader#22]
## Description

Our use case is the following:

We are using `plugin:zip:dir` during our CI to build a .zip package. We don't want to include compiled javascript sources in our version control, so the repo does not contain `public` or `dist` directories.

## Issue

Running `plugin:zip:dir` always strips all files that are not part of the chosen git repository revision.

## Solution

My idea would be to offer some "branch" argument value that makes a copy of the current state instead of using `git archive` to prepare the .zip contents

-----

What do you think? Or do you have any other idea how we could get the above use-case to work? I'd be ready to prepare a PR.

**Comment by moehrenzahn** [comment]
My workaround is to do `git add --force .` and then do a temporary commit.

**Comment by moehrenzahn** [comment]
I have adjusted the issue description since my concrete use-case of including `node_modules` directories in the .zip did not make any sense.

**Comment by shyim** [comment]
Is fixed with https://github.com/FriendsOfShopware/FroshPluginUploader/commit/11ce7bd9e44b71fce6fc541390d9f6aed4fe6576

**Comment by shyim** [comment]
plugin:zip:dir FroshPlatformAdminer/ --strategy=plain => Copies the plugin instead git stuff
plugin:zip:dir FroshPlatformAdminer/ => Copies it using git archive

**Comment by moehrenzahn** [comment]
This looks awesome, thanks for that!
