### ISSUE TITLE
ext:upload --createRelease tag built-commit

### ISSUE THREAD

**Issue by tinect** [FriendsOfShopware/FroshPluginUploader#266]
### Please describe the feature you would like to see implemented.

Having plugins also with packagist accessible, there is a problem the source of the release doesn't contain the compiled data.

Therefore, the PluginUploader could:
- create a commit (f.e. chore: build release) without pushing
- create tag based on the previous commit
- push tag and create release

This makes the build-commit just viewable at the tags, but not in the main repository, and "composer require" will get the correct data.

**Comment by tinect** [comment]
Oh, it looks like you're right.
You mean: we could trigger ext:upload --createRelease after doing tag-stuff on ci-own?

**Comment by shyim** [comment]
Yup
