### ISSUE TITLE
Shopware accounts with multiple companies

### ISSUE THREAD

**Issue by LiaraAlis** [FriendsOfShopware/FroshPluginUploader#274]
### Actual behaviour

If using a shopware account for login that has multiple companies, validating and uploading a plugin can fail.
As far as I can see, it depends on what company was previous selected on account.shopware.com.
If a company was selected that is not a manufacturer the following error can occur:
```
Client error: `GET https://api.shopware.com/producers?companyId=xxxxxx` res  
  ulted in a `400 Bad Request` response:                                       
  {"success":false,"code":"ProducersException-3","detail":"Producer not found  
  "}
```

Otherwise it can fail because the plugin requested is not in this account.

### Expected behaviour

There should be a optional setting to define the company to use.

### Steps to Reproduce?

1. Set a shopware account with multiple companies in environment setting (in the best case a account with multiple companies that are registered as manufacturer)
2. Try to validate or upload a plugin

**Comment by shyim** [comment]
For now I would suggest you to create a dedicated account for this tool.

**Comment by shyim** [comment]
I will deprecate this tool in future and rewrite it in Go. It will be supported there https://github.com/shyim/shopware-cli/issues/1
