### ISSUE TITLE
plugin:zip:dir created files do not pass Automatic Code Review

### ISSUE THREAD

**Issue by moehrenzahn** [FriendsOfShopware/FroshPluginUploader#28]
Creating a plugin .zip file with `plugin:zip:dir` and then uploading it with `plugin:upload` results in an Automatic Code Review failure:

```html
<strong>Basic plugin analysis failed.</strong><br />the required composer.json file was not found, Context: [reason: The essential composer.json file for the plugin was not in the expected folder.
See https://docs.shopware.com/en/shopware-platform-dev-en/internals/plugins/plugin-base-class?category=shopware-platform-dev-en/internals/plugins]
```

My plugin *does* contain a `composer.json`, and so does the `.zip` file created by this tool. The problem is probably because the `.zip` file contains a folder containing all plugin files, instead of having the composer.json at the root of the zip file.

Could this be a bug in the Shopware Store Infrastructure? The plugin `.zip` file *can* be successfully installed in a Shopware 6 installation.

`plugin:validate` does not flag this issue.

**Comment by shyim** [comment]
Maybe your technical plugin name is wrong

**Comment by moehrenzahn** [comment]
Ah, again I learn something new! Thanks, I did not know that the technical name has to match the name of my Plugin class.
