### ISSUE TITLE
Remove deprecation from sw-zip-blacklist

### ISSUE THREAD

**Issue by tinect** [FriendsOfShopware/FroshPluginUploader#282]
### Question

When [.sw-zip-blacklist is deprecated](https://github.com/FriendsOfShopware/FroshPluginUploader/blob/5b240a89630293119a8719e1ac7b78414dc3eb66/src/Components/PluginZip.php#L59), how would someone set stuff to ignore without calling the removing stuff on his own?

I'd like to keep the `sw-zip-blacklist` as it is.

**Comment by shyim** [comment]
https://git-scm.com/docs/gitattributes#_export_ignore

**Comment by tinect** [comment]
But this would not work, when zipping in plain-mode?

**Comment by aragon999** [comment]
Maybe one could add something like a `.zipignore` (maybe a better name to indicate that it is only valid for the plugin pack process), and if that file is present one runs something like `-x@.zipignore` to the ZIP command (in PHP one probably needs to do this via a custom implementation, maybe in `go` this is somewhat easier? :-)
