### ISSUE TITLE
Curl timeout when uploading extension

### ISSUE THREAD

**Issue by avdv** [FriendsOfShopware/FroshPluginUploader#294]
### PHP Version

Docker ghcr.io/friendsofshopware/plugin-uploader:0.3.19

### Shopware Version

6.x

### Actual behaviour

```
$ php /app/bin/pluginupload ext:upload "${PLUGIN_NAME}-${PACKAGE_VERSION}".zip
In CurlFactory.php line 210:
                                                                               
  cURL error 28: Operation timed out after 30000 milliseconds with 0 bytes re  
  ceived (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https:/  
  /api.shopware.com/plugins/13045/binaries                                     
                                                                               
ext:upload [--skipCodeReview] [-s|--skipCodeReviewResult] [--createRelease] [--] <zipPath>
```

Can I somehow increase the timeout limit? Is this a server problem?

### Expected behaviour

Upload would be successful.

### Steps to Reproduce?

Just try to publish a zip.

**Comment by avdv** [comment]
OK, the timeout is set here:
https://github.com/FriendsOfShopware/FroshPluginUploader/blob/0786f432040bc7625dd56356c5ba007245ffb8d3/src/Components/SBP/Client.php#L132

Seems it is not configurable then.

Note that a `php /app/bin/pluginupload ext:list` run right before the ext:upload command always has been successful - I retried our CI job a couple of times -- seems the server is actually not responding within 30 seconds... :worried:

**Comment by shyim** [comment]
maybe network problems on your side? idk

**Comment by avdv** [comment]
> maybe network problems on your side?

It's the same on my local machine at home. And as I said, the request to the same server completes successfully in no time for the `ext:list` command.

I checked out the source and changed the timeout to 300 seconds and it completed successfully... Seems the server is really sluggish. Maybe it is running the checks and this is taking too long before it's starting to respond?

**Comment by avdv** [comment]
BTW, it took a bit more than 30 seconds for the server to respond:
```
real	0m32.977s
user	0m0.242s
sys	0m0.142s
```
Maybe you should increase the timeout (at least for the upload command / when *not* skipping the code checks) or make it configurable.
