### ISSUE TITLE
Extra properties for max and min versions should not be necessary

### ISSUE THREAD

**Issue by mitelg** [FriendsOfShopware/FroshPluginUploader#41]
https://github.com/FriendsOfShopware/FroshPluginUploader/blob/master/src/Components/Generation/ShopwarePlatform/PluginReader.php

this class reads properties from the extra field of the composer.json to determine the min and max versions of the required Shopware version. but this should be unnecessary, as the version field already contains this information. composer knows constrains to define min and max versions, so why store redundant information in the composer.json? which also has the danger, that these two information define different things.

maybe this could be helpful https://github.com/composer/semver

**Comment by shyim** [comment]
I guess that's dead. The relevant code is here https://github.com/FriendsOfShopware/FroshPluginUploader/blob/master/src/Components/Generation/ShopwarePlatform/Plugin.php#L60

Should be cleanuped xD

**Comment by mitelg** [comment]
do we need to take care of deprecations? 🤔 maybe I can go for it

**Comment by shyim** [comment]
Only in command structure and config files. 
I would suggest just remove it without deprecation, cause the code is not called.
Maybe remove it also from the interface, that's only needed for Shopware 5
