### ISSUE TITLE
Error with Plugins starting with the same string!

### ISSUE THREAD

**Issue by bilobait-balleyer** [FriendsOfShopware/FroshPluginUploader#57]
`Producer.php`

The function `getPlugins(string $search)` does not return a unique plugin if there are multiple plugins starting with the same string.

Example:

Plugin 1: BilobaTranslationPro
Plugin 2: BilobaTranslationProMoreLanguages

Both plugins start with `BilobaTranslationPro` and the function returns 2 plugins, which in the function `getPlugin(string $name)` results in a `PluginNotFoundInAccount`.

The `$query['search'] = $search;` command searches too greedy.

**Comment by shyim** [comment]
Good Catch. I will look later

**Comment by shyim** [comment]
This should fix it https://github.com/FriendsOfShopware/FroshPluginUploader/commit/237d5f5d8578370f451366521b6fa69c4c1f0d36
Can you try it?

**Comment by bilobait-balleyer** [comment]
Yes, everything works fine. Thanks!
