### ISSUE TITLE
Docker image is missing PHP extensions

### ISSUE THREAD

**Issue by powli** [FriendsOfShopware/FroshPluginUploader#74]
Currently the docker image only has the PHP extensions installed, which are used by the PluginUploader itself. However if I try to package up plugins that have an additional platform requirement (either directly or in one of their dependencies), the composer installation will fail.

Maybe some of the more common extensions (soap, xml, json, curl etc.) could be included?

**Comment by shyim** [comment]
Maybe it makes just sense to run with ``composer install --no-platform-reqs`` 🤔

**Comment by powli** [comment]
Yes that would also do the trick too.
