### ISSUE TITLE
Shopware 5 plugin validation missing plugin.xml and plugin.png

### ISSUE THREAD

**Issue by ascheider** [FriendsOfShopware/FroshPluginUploader#78]
If i try to validate plugin with the 'php bin/pluginupload plugin:validate ScopRedirecter-v1.0.6.zip' command i get the error that plugin.xml and plugin.png are missing, but the files are present in zip-archive.
The Method hasPluginXml and hasPluginIcon in src/Components/PluginValidator/Shopware5/XmlChecker.php checks file in temporary directory but have no no plugin name in the path:
for example:
/var/folders/78/gkmzp4mx45z0kmx244wyzmn40000gn/T/uploader5f6093e8e2f4c2.30417299/plugin.xml
but file is located under:
/var/folders/78/gkmzp4mx45z0kmx244wyzmn40000gn/T/uploader5f6093e8e2f4c2.30417299/ScopRedirecter/plugin.xml
if i change the file exists check in the method to line bellow, then the check works fine
 if (!file_exists($context->getUnpackedFolder() . '/' . $context->getPlugin()->getName() .  '/plugin.xml'))

**Comment by shyim** [comment]
Can you create an PR? :)

**Comment by ascheider** [comment]
@shyim sure. I will send tomorrow an PR.

**Comment by shyim** [comment]
Thanks
