### ISSUE TITLE
Up to date docker image

### ISSUE THREAD

**Issue by powli** [FriendsOfShopware/FroshPluginUploader#83]
The latest docker image is still on version 0.3.0 (see https://hub.docker.com/r/friendsofshopware/plugin-uploader).

Ideally all release versions would be available as docker image tags and the master branch as `<next_version>-beta` or similar. Maybe use https://github.com/marketplace/actions/docker-publish-semver-tags.

**Comment by shyim** [comment]
https://github.com/orgs/FriendsOfShopware/packages/container/plugin-uploader/76636

Will configure it later also for tags
