### ISSUE TITLE
Command plugin:zip:dir fails, if the branch name is not master. Error: fatal: not a valid object name: master

### ISSUE THREAD

**Issue by ascheider** [FriendsOfShopware/FroshPluginUploader#91]
If you create new repository on github, the branch name is by default not master but main, therefore zip-command fails.
Reference: https://github.com/github/renaming
So the command could also search for the main branch, if master is not present.

**Comment by shyim** [comment]
I would like to use then the current selected branch. Its easier

**Comment by shyim** [comment]
fixed with https://github.com/FriendsOfShopware/FroshPluginUploader/commit/8f265cd3c8ad93a8ae5253b32a8fd406ade0b1a4
