### ISSUE TITLE
Add new function to prepare folder

### ISSUE THREAD

**Issue by tinect** [FriendsOfShopware/FroshPluginUploader#92]
`ext:zip` is preparing (composer install (without shopware), ...) the plugin before zipping.

For this, preparing could be added an own command. This enables users to prepare a folder.
I think, `composer-install`-command would be enough for now.

Background: using the [plugin-dev](https://github.com/FriendsOfShopware/platform-plugin-dev-docker) we have to `composer install` before calling `pack-plugin`, so PluginUploader could make it much easier, cause it extracts shopware/* automatically. Nobody likes to add "composer-ci.json" to make this work. Therefore, you have to manage the dependencies twice.

**Comment by shyim** [comment]
I would not implement here anything until 6.4.0.0. Hopefully we don't need that anymore cause of better Composer integration
